/*
  * @file Prefix Dictionary
*/

var prefixes = {
  'ante'   : 'before',
  'anti'   : 'against',
  'circum' : 'around',
  'co'     : 'with',
  'de'     : 'away from',
  'dis'    : 'opposite',
  'em'     : 'cause to',
  'en'     : 'cause to',
  'epi'    : 'close to',
  'ex'     : 'former',
  'extra'  : 'beyond',
  'fore'   : 'before',
  'homo'   : 'same',
  'hyper'  : 'over',
  'il'     : 'not',
  'im'     : 'not',
  'in'     : 'not',
  'ir'     : 'not',
  'infra'  : 'beneath',
  'inter'  : 'between',
  'intra'  : 'between',
  'macro'  : 'large',
  'micro'  : 'small',
  'mid'    : 'middle',
  'mis'    : 'wrongly',
  'mono'   : 'one',
  'non'    : 'without',
  'omni'   : 'every',
  'para'   : 'beside',
  'post'   : 'after',
  'pre'    : 'before',
  're'     : 'again',
  'semi'   : 'half',
  'sub'    : 'under',
  'super'  : 'above',
  'therm'  : 'heat',
  'trans'  : 'across',
  'tri'    : 'three',
  'un'     : 'not',
  'uni'    : 'one'
}
