/*
  * @file Suffix Dictionary
*/

suffixes = {
  'acy'   : 'state',
  'al'    : 'action of',
  'ance'  : 'state or quality of',
  'ence'  : 'state or quality of',
  'dom'   : 'place or state of being',
  'er'    : 'person or object that does a specific action',
  'or'    : 'person or object that does a specific action',
  'ism'   : 'doctrine or belief',
  'ist'   : 'person or object that does a specific action',
  'ity'   : 'quality of',
  'ty'    : 'quality of',
  'ment'  : 'condition',
  'ness'  : 'state of being',
  'ship'  : 'position held',
  'sion'  : 'state of being',
  'tion'  : 'state of being',
  'ate'   : 'become',
  'en'    : 'become',
  'ify'   : 'make or become',
  'fy'    : 'make or become',
  'ise'   : 'become',
  'ize'   : 'become',
  'able'  : 'capable of being',
  'ible'  : 'capable of being',
  'esque' : 'in a manner of or resembling',
  'ful'   : 'notable for',
  'ic'    : 'having the form or character of',
  'ical'  : 'having the form or character of',
  'ious'  : 'characterised by',
  'ous'   : 'characterised by',
  'ish'   : 'having the quality of',
  'ive'   : 'having the nature of',
  'less'  : 'without',
  'y'     : 'characterised by',
  'ly'    : 'related to or quality',
  'ward'  : 'direction',
  'wards' : 'direction',
  'wise'  : 'in relation to',

}
